# Generated by Django 3.1.12 on 2025-08-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20250826_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booked_at',
        ),
    ]
