# Generated by Django 3.1.12 on 2025-08-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_time',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
